name: Build Check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - run: echo "Build completed successfully"